"""new migration

Revision ID: efbbf5ad1285
Revises: 
Create Date: 2024-11-26 21:43:24.109249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efbbf5ad1285'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('completed_narratives',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('user_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sentence_2', sa.Text(), nullable=True))
        batch_op.alter_column('custom_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_custom_id', ['custom_id'])
        batch_op.drop_column('clause_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clause_text', sa.TEXT(), server_default=sa.text('("")'), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('custom_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('sentence_2')
        batch_op.drop_column('sentence_1')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('completed_narratives',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.Column('isAdmin', sa.BOOLEAN(), nullable=True),
    sa.Column('completed_narratives', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
